#encoding: utf-8
namespace :bootstrap do
 desc "Initialise Data"
 task populate: :environment do
   create_services
 end
end

def create_services
  
  Service.create(primary: "true", title:"Art", left_image: 'art1.jpg', central_image: "art2.jpg", right_image: "art3.jpg", quote:"Handcrafted from single pieces of wood. Each statue, sculpture, model and more is completely unique and one of a kind.", body: "<span style=\"font-weight: normal;text-transform: uppercase;color: #666;line-height: 28px;\">WE HAVE MADE CONNECTIONS WITH MULTIPLE ARTISTS AND CRAFTSMAN IN INDONESIA WHO PLY THEIR TRADE AND PASSION INTO THE MOST STUNNING AND CREATIVE WORKS OF ART. THIS INCLUDES WORKING WITH REVERED ARTIST BARATA SENA WHO SHOWCASES HIS WORK WORLDWIDE, AND WE SELL EXCLUSIVELY AT WOODEN ART WORLD.</span><br><br>All of the pieces of Art are handcrafted to perfection using the highest quality wood and other materials. It is ensured to be a sustainable process throughout every level of production, something understood by us at Wooden Art World and our Artists accordingly. Roots are often used which are a by-product of larger industry who would consider them waste. Our Artists however, see them as potential and craft them accordingly.<br><br>Every single piece is a one off, a unique piece of carefully crafted art which only you can lay claim too. Certificates of Authenticity are provided along with each piece so you truly have a collectible. One of the most stunning types of art we sell are the clothing models. They have a realistic thickness when compared to their real life counterparts yet have been carved painstakingly and with amazing precision by a single artist." )
  Service.create(primary: "true", title:"Furniture", left_image: 'furniture1.jpg', central_image: "furniture2.jpg", right_image: "furniture3.jpg", quote:"Every piece a unique, stunning and functional addition to your home or business.", body: "<span style=\"font-weight:normal;text-transform: uppercase;color: #666;line-height: 28px;\">THE PROCESS OF MAKING A PIECE OF OUR WOODEN FURNITURE BEGINS WITH A LOCAL CRAFTSMAN IN VIETNAM HAND PICKING THE BEST CUTS OF WOOD. AN EXPERT IN THEIR TRADE, THEY THEN CRAFT AND CARVE COMPLETELY UNIQUE FURNITURE WITH NO TWO PIECES THE SAME. THEIR COMMITMENT TO QUALITY AND PRIDE IN THEIR WORK ALLOW THEM TO CREATE SUSTAINABLE AND STUNNING FURNITURE THAT WILL PUT THE WOW INTO YOUR HOME.</span><br><br>Rarely can furniture truly be called one of a kind, but that is exactly what you get from the pieces we sell at wooden Art World. Truly pieces of exceedingly skilled craftsman, each piece starts when a local craftsman hand picks the highest quality of wood. This single piece of wood is then carved and shaped into something functional and stunning. Tables, Chairs and Homeware blends lend both a subtlety and stunning look simultaneously - creating a true centrepiece in your home that does not overpower.<br><br> Each piece of furniture has personally been picked and selected by Wooden Art World experts - ensuring they have been checked for building quality, look and design. The tables and chairs are of the absolute highest quality and you can be ensured to have a piece of furniture that will literally last a lifetime." )

end